---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
data:
{{- $root := . -}}
{{- range $key, $value := .Values.configmap }}
  {{ $key }}: {{ toYaml $value | quote | indent 4 }}
{{- end -}}
