{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps", ""]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["secrets", "configmaps", "services", "ingresses"]
  verbs: ["get", "list", "watch", "delete"]
{{- end -}}
